### ISSUE TITLE
Armenian translations are incorrect

### ISSUE THREAD

**Issue by MateoGreil** [hexorx/countries#622] opened 2020-03-20 10:38 UTC
Hi, some Armenians say me that your translations are not correctly spelled.
I give you the CSV : First tab shows you side by side which ones are corrected. Second tab has the full corrected list.

```
COUNTRY_CODE,OLD,CORRECTED (if needed)
AW,Արուբա,
AF,Աֆղանստան,
AO,Անգոլա,
AI,Անգիլիա,Անգիլա
AX,Ալանդյան կղզիներ,
AL,Ալբանիա,
AD,Անդորա,Անդորրա
AE,Միացյալ Արաբական Էմիրաթներ,Արաբական Միացյալ Էմիրություններ
AR,Արգենտինա,
AM,Հայաստանի Հանրապետութիւն,Հայաստանի Հանրապետություն
AS,Ամերիկյան Սամոա,
AQ,Անտարկտիդա,
TF,Ֆրանսիական Հարավային Տարածքներ,
AG,Անտիգուա-Բարբուդա,Անտիգուա և Բարբուդա
AU,Ավստրալիա,
AT,Ավստրիա,
AZ,Ադրբեջան,
BI,Բուրունդի,
BE,Բելգիա,
BJ,Բենին,
BQ,Բոնեյրե Սինտ Էվստատիուս և Սաբա,
BF,Բուրկինա Ֆասո,
BD,Բանգլադեշ,
BG,Բուլղարիա,
BH,Բահրեյն,
BS,Բահամներ,
BA,Բոսնիա-Հերցեգովինա,Բոսնիա և Հերցեգովինա
BL,Սուրբ Բարդուղիմեոսի կղզի,
BY,Բելոռուս,Բելառուս
BZ,Բելիզ,
BM,Բերմուդյան Կղզիներ,
BO,Բոլիվիա,
BR,Բրազիլիա,
BB,Բարբադոս,
BN,Բրունեյ,
BT,Բութան,
BV,Բուվետ Կղզի,Բուվե Կղզի
BW,Բոտսվանա,
CF,Կենտրոնական Աֆրիկյան Հանրապետություն,
CA,Կանադա,
CC,Կոկոսյան (Քիլինգ) կղզիներ,
CH,Շվեյցարիա,
CL,Չիլի,
CN,Չինաստան,
CI,Կոտ դ'Իվուար,
CM,Կամերուն,
CD,Կոնգո -ի Դեմոկրատական Հանրապետություն,Կոնգոի Դեմոկրատական Հանրապետություն
CG,Կոնգո,
CK,Կուկի Կղզիներ,
CO,Կոլումբիա,
KM,Կոմորոս,Կոմորյան կղզիներ
CV,Կաբո-Վերդե,
CR,Կոստա-Ռիկա,
CU,Կուբա,
CW,Կուրակաո,
CX,Ծննդյան Կղզի,
KY,Կայմանյան Կղզիներ,
CY,Կիպրոս,
CZ,Czechia,Չեխիայի Հանրապետություն
DE,Գերմանիա,
DJ,Ջիբուտի,Ջիբութի
DM,Դոմինիկա,
DK,Դանիա,
DO,Դոմինիկյան Հանրապետություն,
DZ,Ալժիր,
EC,Էկվադոր,
EG,Եգիպտոս,
ER,Էրիտրեա,
EH,Արեվմտյան Սահարա,Արևմտյան Սահարա
ES,Իսպանիա,
EE,Էստոնիա,
ET,Եթովպիա,
FI,Ֆինլանդիա,
FJ,Ֆիջի,
FK,Ֆոլկլոնդյան Կղզիներ,Ֆոլկլենդյան (Մալվինյան) Կղզիներ
FR,Ֆրանսիա,
FO,Ֆարերյան կղզիներ,
FM,Միկրոնեզիայի Ֆեդերային Պետություն,Միկրոնեզիա
GA,Գաբոն,
GB,Մեծ Բրիտանիա,
GE,Վրաստան,
GG,Գերնսի,
GH,Գանա,
GI,Ջիբրալթար,
GN,Գվինեա,
GP,Գվադելուպա,
GM,Գամբիա,
GW,Գվինեա-Բիսաու,
GQ,Հասարակածային Գվինեա,
GR,Հունաստան,
GD,Գրենադա,
GL,Գրենլանդիա,
GT,Գվատեմալա,
GF,Ֆրանսիական Գվիանա,
GU,Գուամ,
GY,Գայանա,
HK,Հոնգ Կոնգ,Հոնկոնգ
HM,Հերդ և Մակդոնալդ Կղզիներ,
HN,Հոնդուրաս,
HR,Խորվաթիա,
HT,Հաիթի,Հայիթի
HU,Հունգարիա,
ID,Ինդոնեզիա,
IM,Մեն Կղզի,
IN,Հնդկաստան,
IO,Հնդկական օվկիանոսի բրիտանական տարածքներ,Բրիտանիայի Հնդկական Օվկիանոսի Տարածք
IE,Իռլանդիա,
IR,Իրան -ի Իսլամական Հանրապետություն,Իրանի Իսլամական Հանրապետություն
IQ,Իրաք,
IS,Իսլանդիա,
IL,Իսրայել,
IT,Իտալիա,
JM,Ջամայկա,Ճամայկա
JE,Ջերսի,
JO,Հորդանան,
JP,Ճապոնիա,
KZ,Ղազախստան,
KE,Քենիա,
KG,Կիրգիզստան,Ղրղզստան
KH,Կամբոջա,
KI,Կիրիբատի,
KN,Սենտ Կիտս-Նեվիս,Սենտ Քիտս և Նևիս
KR,Կորեա Հանարպետություն,Հարավային Կորեա
KW,Քուվեյթ,
LA,Լաոսի Ժողովրդադեմոկրատական հանրապետություն,Լաոս
LB,Լիբանան,
LR,Լիբերիա,
LY,Լիբիա,
LC,Սանտա Լուչիա,Սենտ Լյուսիա
LI,Լիխտենշտեյն,Լիխտենշտայն
LK,Շրի Լանկա,
LS,Լեսոտո,Լեսոթո
LT,Լիտվա,
LU,Լյուքսեմբուրգ,
LV,Լատվիա,
MO,Աոմին,Մակաո
MF,Սուրբ Մարտին (Ֆրանսիական Մաս),Սեն Մարտեն(Ֆրանսիա)
MA,Մարոկո,Մարոկկո
MC,Մոնակո,
MD,Մոլդովա,Մոլդովայի Հանրապետություն
MG,Մադագասկար,
MV,Մալդիվներ,
MX,Մեքսիկա,
MH,Մարշալյան կղզիներ,
MK,Մակեդոնիա Հանրապետություն,Հյուսիսային Մակեդոնիա
ML,Մալի,
MT,Մալթա,
MM,Մյանմա,
ME,Մոնտենեգրո,
MN,Մոնղոլիա,
MP,Հյուսիսային Մարիանայի կղզիներ,Հյուսիսային Մարիանյան Կղզիներ
MZ,Մոզամբիկ,
MR,Մավրիտանիա,
MS,Մոնտսերատ,Մոնսեռա
MQ,Մարտինիկա,
MU,Մավրիտոս,Մավրիկիոս
MW,Մալավի,
MY,Մալայզիա,
YT,Մայոտ,
NA,Նամիբիա,
NC,Նոր Կալեդոնիա,
NE,Նիգեր,
NF,Նոր­ֆոլկ Կղզի,
NG,Նիգերիա,
NI,Նիկարագուա,
NU,Նիուե,
NL,Նիդերլանդեր,Նիդերլանդներ
NO,Նորվեգիա,
NP,Նեպալ,
NR,Նաուրու,
NZ,Նոր Զելանդիա,
OM,Օման,
PK,Պակիստան,
PA,Պանամա,
PN,Պիտքերնյան կղզիներ,Փիտքերնյան կղզիներ
PE,Պերու,
PH,Ֆիլիպիններ,
PW,Պալաու,
PG,Պապուա Նոր Գվինեա,
PL,Լեհաստան,
PR,Պուերտո Ռիկո,
KP,Կորեա Ժողովրդադեմոկրատական Հանրապետություն,
PT,Պորտուգալիա,
PY,Պարագվայ,
PS,"Պաղեստին Պետություն""",Պաղեստին Պետություն
PF,Ֆրանսիական Պոլինեզիա,
QA,Կատար,
RE,Ռեյունյոն,
RO,Ռումինիա,
RU,Ռուսաստանի Դաշնություն,
RW,Ռուանդա,
SA,Սաուդիան Արաբիա,Սաուդյան Արաբիա
SD,Սուդան,
SN,Սենեգալ,
SG,Սինգապուր,
GS,Հարավային Ջորջիա և Հարավային Սանդվիչյան կղզիներ,
SH,Սուրբ Հեղինեի Կղզի Համբարձման և Տրիստան դա Կունյա,Սուրբ Հեղինե
SJ,Սվալբարդ և Յան Մայեն,
SB,Սոլոմոնյան կղզիներ,
SL,Սյերա-Լեոնե,Սիերա Լեոնե
SV,Սալվադոր,
SM,Սան Մարինո,
SO,Սոմալի,
PM,Սեն Պիեռ և Միքելոն,
RS,Սերբիա,
SS,Հարավային Սուդան,
ST,Սան-Թոմե-Փրինսիպի,Սաո Թոմե և Պրինցիպե
SR,Սուրինամ,
SK,Սլովակիա,
SI,Սլովենիա,
SE,Շվեդիա,
SZ,Սվազիլենդ,
SX,Սինթ Մարտեն (Հոլանդական մաս),
SC,Սեյշելներ,
SY,Սիրիայի Արաբական Հանրապետություն,
TC,Թյորքս և Կայկոս կղզիներ,Տուրկս և Կեյկոս Կղզիներ
TD,Չադ,
TG,Տոգո,
TH,Թաիլանդ,
TJ,Տաճիկստան,Տաջիկստան
TK,Տոկելաու,
TM,Թուրքմենստան,
TL,Թիմոր - Լեստե,Արևելյան Թիմոր 
TO,Տոնգա,
TT,Տրինիդադ-Տոբագո,Տրինիդադ և Տոբագո
TN,Թունիս,
TR,Թուրքիա,
TV,Տուվալու,
TW,Թայվան,
TZ,Tanzania,Տանզանիայի Միացյալ Հանրապետություն
UG,Ուգանդա,
UA,Ուկրաինա,
UM,Միացյալ Նահանգների Հեռավոր Փոքր Կղզիներ,"Փոքր Խաղաղօվկիանոսյան Հեռավոր Կղզիներ
(ԱՄՆ)"
UY,Ուրուգվայ,
US,Ամէրիկայի Միացյալ Նահանգնէր,Ամերիկայի Միացյալ Նահանգներ
UZ,Ուզբեկստան,
VA,Սուրբ Քաղաք (Վատիկան),Վատիկան քաղաք-պետություն
VC,Սենտ Վիսենտ-Գրենադիններ,Սենտ Վինսենտ և Գրենադիններ
VE,Վենեսուելա,
VG,Վիրջինյան կղզիներ Բրիտանական,"Վիրջինյան կղզիներ, Բրիտանական"
VI,Վիրջինյան կղզիներ ՄՆ,Վիրջինյան Կղզիներ (ԱՄՆ)
VN,Վիետնամ,
VU,Վանուատու,
WF,Վոլիս և Ֆուտունա,
WS,Սամոա,
YE,Եմեն,
ZA,Հարավային Աֆրիկա,
ZM,Զամբիա,
ZW,Զիմբաբվե,
```

Can you say me if you're going to correct it, or is this not a real issue for you ?
Thank you, Mat.

[Country List - Armenian.xlsx](https://github.com/hexorx/countries/files/4359117/Country.List.-.Armenian.xlsx)

**Comment by pmor** [comment] 2020-03-20 11:12
If I'm not mistaken (maybe @rposborne can confirm this) that data comes from https://github.com/hexorx/countries/blob/d788f8ea76236e8ad08d33d5951b720f230ba5af/lib/countries/cache/locales/hy.json which is cached data from the Unicode CLDR repo here - https://github.com/unicode-org/cldr/blob/master/common/subdivisions/hy.xml

In that case, the issue is with CLDR's data, but can be patched over with a correction in https://github.com/hexorx/countries/blob/d788f8ea76236e8ad08d33d5951b720f230ba5af/lib/countries/data/translation_corrections.yaml

**Comment by MateoGreil** [comment] 2020-03-20 13:45
Thank you, I'll patch locally this.
I just do not understand what is cached from the Unicode CLDR repo, nothing is common.
But I close this issue, you're not able to correct it.

**Comment by pmor** [comment] 2020-03-20 13:50
@MateoGreil I might not have explained myself properly, I meant to say that it can be fixed on this gem by adding corrections to `translations_corrections.yaml`

The gem is somewhat unmaintained at this time and looking for more maintainers, I've offered help, but @hexorx would have to give me access to the repository, so for now, all I can do is help triage issues. 

Please reopen the issue, and someone will try to address it once there are more people with access to the repository.

**Comment by MateoGreil** [comment] 2020-03-20 13:54
Ok, in wait for the correction in this gem, I'm going to add a countries_corrections.yml in my project config and load it in my initializers. I think this is going to work, just like in this gem.

**Comment by MateoGreil** [comment] 2020-03-20 16:24
https://github.com/hexorx/countries/pull/623

**Comment by MateoGreil** [comment] 2020-03-23 10:18
Ok I think this is just a problem with the usage of iso-codes project (https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/master/iso_3166-1/hy.po#L24), there is two name for one country, one official and one 'familiar'. Just for some country, they would like to use the Official Name. Is this donable with your library without forking it ?

**Closed** 2020-03-23 14:00 UTC
