### ISSUE TITLE
Problem with ISO3166::Country::Data after update to version 0.11.5

### ISSUE THREAD

**Issue by sergey-kucher** [hexorx/countries#278] opened 2015-07-10 12:31 UTC
When trying to [access](https://github.com/joost/phony_rails/blob/v0.12.8/lib/phony_rails.rb#L10) ISO3166::Country::Data constant we have top level Data constant instead.

Next warning appears: `toplevel constant Data referenced by ISO3166::Country::Data`
And then error: `undefined method `[]' for Data:Class`

**Comment by monfresh** [comment] 2015-07-10 20:20
+1 I'm seeing this as well. Reverting to 0.11.4 fixes the issue.

**Comment by monfresh** [comment] 2015-07-10 20:35
So, the issue is that the phony_rails gem is depending on the countries gem, and is accessing the data in the old way via [ISO3166::Country::Data](https://github.com/joost/phony_rails/blob/master/lib/phony_rails.rb#L10). However in 0.11.5, [`Data` was changed to `Setup.data`](https://github.com/hexorx/countries/commit/bdc3d90c34accb60cc2a33d833d54c28d5bdeb80).

**Comment by monfresh** [comment] 2015-07-11 15:10
@sergey-kucher I submitted a [PR](https://github.com/joost/phony_rails/pull/104) to fix this, and it was merged. Joost said he will release a new version soon. In the meantime, you can point the gem to the phony_rails repo, like this:
```ruby
gem 'phony_rails', github: 'joost/phony_rails'
```

You should probably close this issue here since it's not a countries issue, but a phony_rails issue which has now been fixed.

**Closed** 2015-07-12 07:09 UTC

**Comment by sergey-kucher** [comment] 2015-07-12 07:12
@monfresh Thank you

**Comment by bbnnt** [comment] 2015-11-09 10:12
is it related ?
getting the following error : 
`undefined method `[]' for #<ISO3166::Country:0x00000102ddb028>`

while calling `ISO3166::Country.all`

**Comment by rposborne** [comment] 2015-11-13 15:34
@bbnnt Could you start another issue? I don't think this is related but am happy to help figure out what's going on.
