### ISSUE TITLE
Registering new countries in initializers overrides everything

### ISSUE THREAD

**Issue by madshargreave** [hexorx/countries#358] opened 2016-08-01 13:57 UTC
Hi

If I register a new country in an initializer file, it overrides all the other countries in the gem.

For example

```
.../initializers/countries.rb
ISO3166::Data.register(
        alpha2: "IC",
        name: 'Spain - Canary Islands',
        translations: {
          'en' => 'Spain - Canary Islands'
        }
      )
```

Will result in `Country.all` only returning this country.

Works fine if I manually register the country before calling the `Country.all`

**Comment by rposborne** [comment] 2016-08-01 23:10
This appears to be a duplicate of #353. 

Will close in favor of #353

**Closed by rposborne** 2016-08-01 23:10 UTC
