### ISSUE TITLE
Language code in subdivisions names

### ISSUE THREAD

**Issue by daniel-rikowski** [hexorx/countries#281] opened 2015-07-21 13:43 UTC
I noticed that the subdivision names of Switzerland and Belgium (for example) contain the language code of the official language of that subdivision, e.g. `Bern (de)` or `Antwerpen (nl)`.

On the other hand subdivisions of other countries with multiple official languages are lacking that information, e.g. Spain, Canada or India. 

Personally I don't think the language code belongs into the `name` attribute. A (future) translation hash would be much more suitable.

What is the long term goal here? Do they have to stay or do you accept pull requests to remove them?

**Comment by rposborne** [comment] 2015-09-17 13:45
This is a duplicate of #56 

As for the content, think the language code is pretty tacky to be in the string name.   Should go,  but we need that data.   I need to wrap my ahead around good design for storing the growing complexity of the subdivision data.

**Closed by rposborne** 2015-09-17 13:45 UTC
