### ISSUE TITLE
Country.find_country_by_name('Canada') returns Uganda

### ISSUE THREAD

**Issue by SergeyBukhman** [hexorx/countries#305] opened 2015-10-27 08:04 UTC
title, pretty much

**Comment by SergeyBukhman** [comment] 2015-10-27 08:16
Turns out it also returns Rwanda. It's because of a bad xh translation that says 'Canada' somewhere.

**Comment by rposborne** [comment] 2015-11-01 20:13
@SergeyBukhman what version are you using... we had some bad translation_names sneak in.  But have since turned this feature of, (where name is so aliased to translated_names)

**Comment by rposborne** [comment] 2015-11-13 15:15
@SergeyBukhman since we have a regression test for this exact example I am going to close this out. If you are still having issues please let me know.

**Closed by rposborne** 2015-11-13 15:15 UTC
